name: Create an issue on commit

on: 
-  push

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue using REST API
      run: |
         curl --request POST \
         --url https://api.github.com/repos/${{ github.repository }}/issues \
         --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         -H "Accept: application/vnd.github+json" \
         --data '{
         "title": "Automated Issue for commit: ${{ github.sha }}",
         "body": "This issue was created by github actions workflow **${{ github.workflow }}** \n\n The commit hash was: _${{ github.sha }}_."
         }'
         
         
